Added a proper working revalidateTag functionality to redis-stack handler
caching-tools/next-shared-cache pull request #332
Opened 2024-02-08 20:28 UTC by MaKTaiL

"revalidateTag" wasn't working correctly because it wasn't deleting the keys associated with the tag.

- Added index creation for searching tags accross multiple keys
- Added function for sanitizing tag string (to avoid errors with index search)
- revalidateTag finds and deletes all keys with the requested tag

2024-02-09 13:51 UTC, better-salmon commented
Hi @MaKTaiL, thank you for your contribution. The current implementation is fine. Instead of deleting cache entries, we are now collecting a list of tags that have been revalidated. When the Next.js Server retrieves values from the cache store, we check if a particular cache key was revalidated before serving it to the Next.js server. This was done to support pages from Pages Router. I'm currently working on a major refactoring for this part of the library. Once I've completed that, I'll revisit your PR. Thanks again!

2024-02-09 13:59 UTC, MaKTaiL commented
> Hi @MaKTaiL, thank you for your contribution. The current implementation is fine. Instead of deleting cache entries, we are now collecting a list of tags that have been revalidated. When the Next.js Server retrieves values from the cache store, we check if a particular cache key was revalidated before serving it to the Next.js server. This was done to support pages from Pages Router. I'm currently working on a major refactoring for this part of the library. Once I've completed that, I'll revisit your PR. Thanks again!

The current implementation does not do anything when you request a revalidateTag, it only updates the time the tag was "updated". The cache entry values remain the same unless you delete the key from the Redis database. Deleting the key will signal NextJS that there is no cache entry for it which will force a revalidation of the fetch results which will then be saved again with new values on Redis.

2024-02-20 15:49 UTC, better-salmon commented
Hey @MaKTaiL! Sorry for the delay. Please change the target branch of this PR to the [canary-1.0.0-rc](https://github.com/caching-tools/next-shared-cache/tree/canary-1.0.0-rc).

2024-02-20 18:46 UTC, MaKTaiL commented
Hi @better-salmon! I just changed target branch, merged and resolved conflicts. I saw the changes you've made and it appears to be a working revalidateTag example but I'm concerned about the race condition of storing the tags in a map. If multiple people request different tags for revalidation, the tags' map (stored in a key formed with keyPrefix + revalidatedTagsKey) has a huge chance of conflicting between requests since both will be updating it at the same time. Whichever updates last will be the winner.

Let's look at this scenario:

Tags' map looks like this:

``` json
{
  "tag1": ["key1", "key2"],
  "tag2": ["key3', "key4"],
  "tag3": ["key5', "key6"],
}
```

- User 1 requests revalidation of tag1, and User 2 requests revalidation of tag2, both at the same time.
- Both requests retrieve the same copy of the tags map
- First request removes tag1 from map and sends it back to Redis.
- Second request removes tag2 and sends it back to Redis.
- Final map will look like this:

``` json
{
  "tag1": ["key1", "key2"],
  "tag3": ["key5', "key6"],
}
```

You see tag1 still remains because it wasn't aware of the User 1 request. Now imagine a scenario with thousand of people doing the same thing.
That said I think using an index for the tags is the better, faster and safer solution.
For using an index it is paramount that we sanitize the tags (remove any chars that Redis does not accept in query operations).
I adapted the code for this while also using the sharedTagsKey you implemented. Let me know what you think.

2024-02-20 23:05 UTC, better-salmon commented
I oversaw this case during the major refactoring. Thank you! I'll review and merge your solution soon.

2024-02-25 16:15 UTC, better-salmon commented
@MaKTaiL hi! I have ended the work on the new API. But I accidentally made some force pushes to the `canary-1.0.0-rc` branch, please rebase your PR one more time. I'm sorry.

And I want you to make some fixes:

- Run npm run codestyle:fix before committing.
- Use full names for variables and arguments e.g. `query.documents.map((doc) => doc.id)` will become `query.documents.map((document) => document.id)` or `query.documents.map(({ id }) => id)`
- Remove the sharedTagsKey option from the redis-stack Handler options. It seems obsolete with indexing.

2024-02-26 08:59 UTC, better-salmon commented
Actually, I can merge `canary-1.0.0-rc` to `canary`, and it will be easier for you to merge your PR to the `canary` branch.

2024-02-26 10:24 UTC, better-salmon commented
Closing your pull request was not intended. Please rebase it one last time to the `canary` with the requested changes. You've done a great job!

2024-02-26 11:06 UTC, MaKTaiL commented
Hi @better-salmon , sorry for the late reply. I was busy this weekend. I'll merge the changes as soon as I can.

2024-02-26 11:47 UTC, better-salmon commented
It's ok! I will wait 👍

2024-02-26 12:13 UTC, MaKTaiL commented
@better-salmon All good! I've done what you asked:

- Run npm run codestyle:fix before committing.
- Use full names for variables and arguments e.g. query.documents.map((doc) => doc.id) will become query.documents.map((document) => document.id) or query.documents.map(({ id }) => id)
- Remove the sharedTagsKey option from the redis-stack Handler options. It seems obsolete with indexing.

2024-02-26 12:28 UTC, better-salmon requested changes
Please, remove some outdated code I've commented

2024-02-26 12:28 UTC, better-salmon commented on packages/cache-handler/src/handlers/server.ts
> +            const _isRouteKind = cacheHandlerValue.value?.kind === 'ROUTE';
Delete this line please

2024-02-26 12:28 UTC, better-salmon commented on packages/cache-handler/src/handlers/redis-stack.ts
>  }: RedisCacheHandlerOptions<T>): Promise<Handler> {
```suggestion
}: Omit<RedisCacheHandlerOptions<T>, 'sharedTagsKey'>): Promise<Handler> {
```

2024-02-26 12:28 UTC, better-salmon commented on packages/cache-handler/src/handlers/redis-stack.ts
> +
```suggestion
            cacheHandlerValue.tags = cacheHandlerValue.tags.map(sanitizeTag);

```

2024-02-26 12:28 UTC, better-salmon commented on packages/cache-handler/src/handlers/redis-stack.ts
> +                preparedCacheValue as unknown as RedisJSON,
```suggestion
                cacheHandlerValue as unknown as RedisJSON,
```

2024-02-26 12:28 UTC, better-salmon commented on packages/cache-handler/src/handlers/redis-stack.ts
```suggestion
            const expireCacheValue = cacheHandlerValue.lifespan
                ? client.expireAt(options, keyPrefix + key, cacheHandlerValue.lifespan.expireAt)
                : undefined;

```

2024-02-26 12:30 UTC, better-salmon commented on packages/cache-handler/src/handlers/redis-stack.ts
> +
I'm sorry, suggestion is confusing. I meant that there is no need in creating `preparedCacheValue` and checking for the `ROUTE` kind anymore.

2024-02-26 12:40 UTC, MaKTaiL commented
@better-salmon For some reason it wasn't letting me apply your suggestions here so I manually edited them and pushed the changes. I think that is all. Let me know if there are any more fixes to apply.

2024-02-26 12:52 UTC, better-salmon requested changes

2024-02-26 12:52 UTC, better-salmon commented on packages/cache-handler/src/handlers/redis-stack.ts
Let's add check for `keysToDelete.length`. If there is no keys to revalidate there is no need to call `client.del`.

```js
if (keysToDelete.length === 0) {
    return;
}
```

2024-02-26 13:02 UTC, better-salmon approved these changes

2024-02-26 13:24 UTC, merged

2024-02-26 13:29 UTC, better-salmon commented
Thank you for your contribution!