Add ability to disable Redis operations timeout
caching-tools/next-shared-cache pull request #639
Opened 2024-07-15 16:02 UTC by ElyDotDev

There is a known bug in the Redis package, that will be fixed in version 5, which is in the alpha stage. (https://github.com/redis/node-redis/issues/2498)

The issue is about the usage of AbortSignal. When it is used, if the Redis connection encounters an error, like the Redis server gets offline, an unhandled error will be thrown. This error will cause an issue with the reconnection of the client, and it'll put the Redis client into a limbo stage that will not recover unless the Next.js app restarts.

This PR will address this issue by giving the ability to disable the Redis operations timeout totally, by setting the value of `timeoutMS: 0` for `redis-string` and `redis-stacks` handlers.

2024-07-18 09:43 UTC, better-salmon commented on packages/cache-handler/src/helpers/get-timeout-redis-command-options.ts
> +    return commandOptions(!!timeoutMs && timeoutMs !== 0 ? { signal: AbortSignal.timeout(timeoutMs) } : {});
Let's rely on Typescript and JSDoc here and do not check `!!timeoutMs`. Also let's use more straightforward approach using `if` statement.

```suggestion
    if (timeoutMs === 0) {
        return commandOptions({});
    }

    return commandOptions({ signal: AbortSignal.timeout(timeoutMs) });
```

2024-07-18 09:44 UTC, better-salmon requested changes
Hello @ElyDotDev! Thank you for contribution! I've just leave a suggestion. Could you please address it and then I'll merge your PR.

2024-07-18 22:39 UTC, ElyDotDev commented
Thanks @better-salmon. I applied your suggestion. Everything seems fine. Thanks again for your effort.

2024-07-19 11:18 UTC, better-salmon approved these changes
Thank you for contribution!

2024-07-19 11:28 UTC, merged

2024-07-19 12:45 UTC, better-salmon commented
@ElyDotDev, I've released version 1.4.2 with your contribution!